Repository LikeMindsCommunity/LikeMinds-ReactNative-Chat-Sample-App, pull requests merged in 2023-12, with the labels that each got.

#190 [LM-10094] GIF Support
  App.tsx
  ChatSX/audio/Controls.ts
  ChatSX/audio/TrackPlayerServices.ts
  ChatSX/aws-exports.js
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/HomeFeedItem/styles.ts
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/InputBoxProps.ts
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/components/ReplyConversations/styles.ts
  ChatSX/constants/Strings.ts
  ChatSX/enums/DocumentType.ts
  ChatSX/screens/CarouselScreen/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ChatRoom/styles.ts
  ChatSX/screens/FIleUpload/index.tsx
  android/app/build.gradle
  android/build.gradle
  package.json
Labels: feature

#199 Version changed - v1.8.0
  .env
  ChatSX/setup.ts
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: release

#201 Version changed - v1.8.0
  package.json
Labels: release

#204 [LM-10398] Removal of unused screens
  ChatSX/navigation/SwitchComponent/index.tsx
Labels: feature

#205 [LM-10289] Filter State Messages
  index.js
Labels: feature

#203 [LM-10263] Notification Stack
  App.tsx
  ChatSX/LMChatApp.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/credentials.ts
  ChatSX/db/schemas/UserSchema.ts
  ChatSX/navigation/SwitchComponent/index.tsx
  ChatSX/notifications/index.ts
  ChatSX/notifications/models/chatroomData.ts
  ChatSX/notifications/models/index.tsx
  ChatSX/notifications/routes.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  Sample/index.tsx
  index.js
  package.json
Labels: feature

#206 [LM-10514] Product Signoff Bugs v1.9.0
  App.tsx
  ChatSX/commonFuctions/index.tsx
  ChatSX/commonFuctions/model.ts
  ChatSX/components/ExploreFeedItem/index.tsx
  ChatSX/constants/Strings.ts
  ChatSX/notifications/index.ts
  index.js
Labels: bug

#207 Version Changed - v1.9.0
  .env
  android/app/build.gradle
  ios/Scalix/Info.plist
  package.json
Labels: release

#208 Release/v1.9.0
  .env
  App.tsx
  ChatSX/LMChatApp.tsx
  ChatSX/commonFuctions/index.tsx
  ChatSX/commonFuctions/model.ts
  ChatSX/components/ExploreFeedItem/index.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/constants/Strings.ts
  ChatSX/credentials.ts
  ChatSX/db/schemas/UserSchema.ts
  ChatSX/navigation/SwitchComponent/index.tsx
  ChatSX/notifications/index.ts
  ChatSX/notifications/models/chatroomData.ts
  ChatSX/notifications/models/index.tsx
  ChatSX/notifications/routes.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  Sample/index.tsx
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: release
