Repository LikeMindsCommunity/LikeMinds-ReactNative-Chat-Sample-App, pull requests merged in 2023-10, with the labels that each got.

#159 [LM-9706] Shimmer in Home Feed and DMFeed and few remaining keys flow
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/store/actions/chatroom.ts
  ChatSX/store/types/types.ts
  package.json
Labels: enhancement

#162 [LM-9707] Conversation Flow
  App.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/ExploreFeedItem/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/customModals/RejectDMRequest/index.tsx
  ChatSX/enums/chatoomChatRequestStateEnum.ts
  ChatSX/enums/chatroomType.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ExploreFeed/index.tsx
  ChatSX/screens/FIleUpload/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/store/actions/chatroom.ts
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/reducers/fileUploadReducer.ts
  ChatSX/store/reducers/homefeedReducer.ts
  ChatSX/store/types/types.ts
  ChatSX/utils/homeFeedUtils.ts
  ChatSX/utils/syncChatroomApi.ts
  android/gradle.properties
Labels: enhancement

#166 [LM-9897] Peer testing bugs
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/Poll/PollConversationView/index.tsx
  ChatSX/components/TaggingView/utils.ts
  ChatSX/customModals/SendDMRequest/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/store/reducers/homefeedReducer.ts
Labels: bug

#167 [LM-9897] Peer Testing Bugs
  ChatSX/assets/images/imagePlaceholder.jpeg
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/ExploreFeedFilters/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/constants/Styles.ts
  ChatSX/customModals/styles.ts
  ChatSX/enums/DocumentType.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ExploreFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/ViewParticipants/index.tsx
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/reducers/explorefeedReducer.ts
  ChatSX/store/types/types.ts
Labels: bug

#168 Release v1.4.0
  ChatSX/assets/images/imagePlaceholder.jpeg
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/ExploreFeedFilters/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/constants/Styles.ts
  ChatSX/customModals/styles.ts
  ChatSX/enums/DocumentType.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ExploreFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/ViewParticipants/index.tsx
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/reducers/explorefeedReducer.ts
  ChatSX/store/types/types.ts
Labels: release

#161 [LM-9637] Chatroom sharing & deep linking
  App.tsx
  ChatSX/Models/PollModels/index.tsx
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/components/ParseDeepLink/index.ts
  ChatSX/components/ParseDeepLink/models/DeepLinkRequest.ts
  ChatSX/components/ParseDeepLink/models/DeepLinkResponse.ts
  ChatSX/components/ParseDeepLink/models/index.tsx
  ChatSX/components/Poll/CreatePollScreen/index.tsx
  ChatSX/components/Poll/CreatePollUI/index.tsx
  ChatSX/components/Poll/PollConversationUI/index.tsx
  ChatSX/components/Poll/PollConversationView/index.tsx
  ChatSX/components/Poll/models/CreatePoll.ts
  ChatSX/components/Poll/models/CreatePollCallbacks.ts
  ChatSX/components/Poll/models/CreatePollProps.ts
  ChatSX/components/Poll/models/CreatePollStateProps.ts
  ChatSX/components/Poll/models/Poll.ts
  ChatSX/components/Poll/models/PollConversationUIProps.ts
  ChatSX/components/Poll/models/PollConversationViewCallbacks.ts
  ChatSX/components/Poll/models/PollConversationViewProps.ts
  ChatSX/components/Poll/models/PollConversationViewState.ts
  ChatSX/components/Poll/models/index.tsx
  ChatSX/constants/Regex.ts
  ChatSX/constants/Strings.ts
  ChatSX/customModals/RejectDMRequest/index.tsx
  ChatSX/db/models/UserSchemaResponse.ts
  ChatSX/db/models/index.tsx
  ChatSX/enums/ChatroomActions.ts
  ChatSX/enums/ChatroomChatRequestState.ts
  ChatSX/enums/index.tsx
  ChatSX/navigation/SwitchComponent.tsx
  ChatSX/notifications/models/index.tsx
  ChatSX/notifications/models/routeParams.ts
  ChatSX/notifications/routes.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/shareUtils/index.ts
  ChatSX/shareUtils/models/ShareChatroomRequest.ts
  ChatSX/shareUtils/models/index.tsx
  ChatSX/store/reducers/homefeedReducer.ts
  RootNavigation.js
  Sample/index.tsx
  android/app/src/main/AndroidManifest.xml
  ios/Scalix/AppDelegate.mm
  ios/Scalix/Info.plist
  ios/Scalix/Scalix.entitlements
  tsconfig.json
Labels: enhancement

#165 [LM-9638] Camera Handling
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/InputBoxProps.ts
  ChatSX/components/InputBox/models/LaunchActivityProps.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/enums/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/utils/permissions.ts
Labels: enhancement

#169 Product signoff bugs
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/components/TopTabNavigator/index.tsx
  ChatSX/components/TopTabNavigator/styles.ts
  ChatSX/screens/ChatRoom/index.tsx
Labels: bug

#170 LocalDB Product Signoff bugs
  App.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/navigation/SwitchComponent.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/utils/syncChatroomApi.ts
  index.js
  ios/Scalix/Info.plist
Labels: bug

#172 Changed import of enum to correct value
  ChatSX/enums/index.tsx
Labels: bug

#173 Release/v1.5.0
  ChatSX/enums/index.tsx
Labels: bug

#174 [LM-9460] Analytics
  ChatSX/analytics/LMChatAnalytics.ts
  ChatSX/assets/chatSchema/index.ts
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/ExploreFeedFilters/index.tsx
  ChatSX/components/ExploreFeedItem/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/InputBoxProps.ts
  ChatSX/components/Messages/index.tsx
  ChatSX/components/Poll/CreatePollScreen/index.tsx
  ChatSX/components/PollResult/index.tsx
  ChatSX/components/ReactionGridModal/index.tsx
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/components/TopTabNavigator/index.tsx
  ChatSX/enums/Events.ts
  ChatSX/enums/Keys.ts
  ChatSX/enums/MediaType.ts
  ChatSX/enums/Sources.ts
  ChatSX/enums/index.tsx
  ChatSX/notifications/routes.ts
  ChatSX/screens/AddParticipants/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ExploreFeed/index.tsx
  ChatSX/screens/FIleUpload/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/screens/ReportMessage/index.tsx
  ChatSX/screens/ViewParticipants/index.tsx
  ChatSX/shareUtils/index.ts
  ChatSX/utils/analyticsUtils.ts
Labels: enhancement

#178 [LM-9639] Link Preview
  ChatSX/assets/images/defaultLinkPreview.png
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/OgTags.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/LinkPreview/index.tsx
  ChatSX/components/LinkPreview/models/LinkPreviewBoxProps.ts
  ChatSX/components/LinkPreview/models/LinkPreviewProps.ts
  ChatSX/components/LinkPreview/models/index.ts
  ChatSX/components/LinkPreview/styles.ts
  ChatSX/components/Messages/index.tsx
  ChatSX/components/linkPreviewBox/index.tsx
  ChatSX/components/linkPreviewInputBox/index.tsx
  ChatSX/components/linkPreviewInputBox/models/LinkPreviewInputBoxProps.ts
  ChatSX/components/linkPreviewInputBox/models/index.ts
  ChatSX/constants/Regex.ts
  ChatSX/enums/index.tsx
  ChatSX/store/reducers/chatroomReducer.ts
Labels: enhancement

#175 [LM-9641] Image Cropping
  ChatSX/assets/images/crop_icon3x.png
  ChatSX/assets/images/rotate_icon3x.png
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/LinkPreview/index.tsx
  ChatSX/components/LinkPreview/models/LinkPreviewProps.ts
  ChatSX/components/Messages/index.tsx
  ChatSX/constants/Screens.ts
  ChatSX/constants/Strings.ts
  ChatSX/navigation/SwitchComponent/index.tsx
  ChatSX/navigation/SwitchComponent/models/ImageCropScreen.ts
  ChatSX/navigation/SwitchComponent/models/RootStackParamsList.ts
  ChatSX/navigation/SwitchComponent/models/index.ts
  ChatSX/screens/FIleUpload/index.tsx
  ChatSX/screens/FIleUpload/styles.ts
  ChatSX/screens/ImageCrop/index.tsx
  ChatSX/screens/ImageCrop/models/ImageCropScreenProps.ts
  ChatSX/screens/ImageCrop/models/index.ts
  ChatSX/screens/ImageCrop/styles.ts
  ios/Podfile
  package.json
Labels: enhancement
