Repository LikeMindsCommunity/LikeMinds-ReactNative-Chat-Sample-App, pull requests merged in 2023-07, with the labels that each got.

#134 [LM-9207] Hotfix UUID
  .env
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/TaggingView/utils.ts
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/FIleUpload/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/ViewParticipants/index.tsx
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: hotfix

#140 [LM-9000] Tagged Member related bugs
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/TaggingView/index.tsx
  ChatSX/components/TaggingView/utils.ts
Labels: bug

#141 [LM-9262] Tagging Bugs
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/TaggingView/utils.ts
Labels: bug

#142 [LM-9163] Poll API and Logics
  ChatSX/Models/PollModels/index.tsx
  ChatSX/assets/images/add_options3x.png
  ChatSX/assets/images/expand_arrow3x.png
  ChatSX/assets/images/minimize_arrow3x.png
  ChatSX/assets/images/poll_icon3x.png
  ChatSX/assets/images/sort_down3x.png
  ChatSX/assets/images/submit_click3x.png
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/Messages/index.tsx
  ChatSX/components/Messages/styles.ts
  ChatSX/components/Poll/CreatePollScreen/index.tsx
  ChatSX/components/Poll/CreatePollUI/index.tsx
  ChatSX/components/Poll/PollConversationUI/index.tsx
  ChatSX/components/Poll/PollConversationView/index.tsx
  ChatSX/components/Poll/index.tsx
  ChatSX/components/Poll/styles.ts
  ChatSX/components/PollResult/index.tsx
  ChatSX/components/PollResult/styles.ts
  ChatSX/constants/Screens.ts
  ChatSX/constants/Strings.ts
  ChatSX/constants/Styles.ts
  ChatSX/customModals/ActionListModel/index.tsx
  ChatSX/customModals/ActionListModel/styles.ts
  ChatSX/customModals/AddOptionModal/index.tsx
  ChatSX/customModals/AnonymousPoll/index.tsx
  ChatSX/customModals/styles.ts
  ChatSX/navigation/SwitchComponent.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/store/actions/homefeed.ts
  package.json
Labels: enhancement

#143 [LM-9321] Poll sign-off bugs
  .env
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/Poll/CreatePollUI/index.tsx
  ChatSX/components/Poll/styles.ts
  android/app/build.gradle
  android/app/src/main/res/values/styles.xml
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: bug

#144 Release v1.2.0
  .env
  ChatSX/Models/PollModels/index.tsx
  ChatSX/assets/images/add_options3x.png
  ChatSX/assets/images/expand_arrow3x.png
  ChatSX/assets/images/minimize_arrow3x.png
  ChatSX/assets/images/poll_icon3x.png
  ChatSX/assets/images/sort_down3x.png
  ChatSX/assets/images/submit_click3x.png
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/Messages/index.tsx
  ChatSX/components/Messages/styles.ts
  ChatSX/components/Poll/CreatePollScreen/index.tsx
  ChatSX/components/Poll/CreatePollUI/index.tsx
  ChatSX/components/Poll/PollConversationUI/index.tsx
  ChatSX/components/Poll/PollConversationView/index.tsx
  ChatSX/components/Poll/index.tsx
  ChatSX/components/Poll/styles.ts
  ChatSX/components/PollResult/index.tsx
  ChatSX/components/PollResult/styles.ts
  ChatSX/components/TaggingView/index.tsx
  ChatSX/components/TaggingView/utils.ts
  ChatSX/constants/Screens.ts
  ChatSX/constants/Strings.ts
  ChatSX/constants/Styles.ts
  ChatSX/customModals/ActionListModel/index.tsx
  ChatSX/customModals/ActionListModel/styles.ts
  ChatSX/customModals/AddOptionModal/index.tsx
  ChatSX/customModals/AnonymousPoll/index.tsx
  ChatSX/customModals/styles.ts
  ChatSX/navigation/SwitchComponent.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/store/actions/homefeed.ts
  android/app/build.gradle
  android/app/src/main/res/values/styles.xml
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: release
