Repository LikeMindsCommunity/LikeMinds-ReactNative-Chat-Sample-App, pull requests merged in 2023-11, with the labels that each got.

#180 [LM-10089] Product Signoff Bugs
  ChatSX/components/InputBox/styles.ts
  ChatSX/screens/ChatRoom/index.tsx
Labels: bug

#181 Release/v1.6.0
  .env
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: enhancement

#185 [LM-9635] Chatroom Topic
  ChatSX/assets/images/link_icon.png
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/InputBoxProps.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/db/models/UserInfo.ts
  ChatSX/db/models/index.tsx
  ChatSX/enums/GetConversationsType.ts
  ChatSX/enums/MemberState.ts
  ChatSX/enums/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ChatRoom/styles.ts
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/types/types.ts
  ChatSX/utils/chatroomUtils.ts
  ChatSX/utils/syncChatroomApi.ts
Labels: enhancement

#184 [LM-9962] Voice Note Animation Support
  App.tsx
  ChatSX/assets/images/left_chevron_icon3x.png
  ChatSX/assets/images/up_chevron_icon3x.png
  ChatSX/assets/lottieJSON/delete.json
  ChatSX/audio/Controls.ts
  ChatSX/audio/TrackPlayerServices.ts
  ChatSX/audio/Utils.ts
  ChatSX/audio/index.ts
  ChatSX/aws-exports.js
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/AttachmentConversations/styles.ts
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/VoiceNotesPlayerProps.ts
  ChatSX/components/InputBox/models/VoiceNotesProps.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/constants/Strings.ts
  ChatSX/enums/DocumentType.ts
  ChatSX/enums/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/types/types.ts
  ChatSX/utils/permissions.ts
  ChatSX/utils/syncChatroomApi.ts
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  index.js
  ios/Podfile
  ios/Scalix-Bridging-Header.h
  package.json
Labels: enhancement

#179 [LM-9963] Play-pause management
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/VoiceNotesPlayerProps.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
Labels: enhancement

#177 [LM-9636] Voice Notes
  App.tsx
  ChatSX/assets/images/cross_circle_icon3x.png
  ChatSX/assets/images/left_chevron_icon3x.png
  ChatSX/assets/images/mic_icon3x.png
  ChatSX/assets/images/pause_icon3x.png
  ChatSX/assets/images/play_icon3x.png
  ChatSX/assets/images/record_icon3x.png
  ChatSX/assets/images/retry_cloud_upload3x.png
  ChatSX/assets/images/stop_recording_icon3x.png
  ChatSX/assets/images/up_chevron_icon3x.png
  ChatSX/assets/lottieJSON/delete.json
  ChatSX/audio/Controls.ts
  ChatSX/audio/TrackPlayerServices.ts
  ChatSX/audio/Utils.ts
  ChatSX/audio/index.ts
  ChatSX/aws-exports.js
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/AttachmentConversations/styles.ts
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/VoiceNotesPlayerProps.ts
  ChatSX/components/InputBox/models/VoiceNotesProps.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/constants/Strings.ts
  ChatSX/enums/DocumentType.ts
  ChatSX/enums/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/types/types.ts
  ChatSX/utils/permissions.ts
  ChatSX/utils/syncChatroomApi.ts
  Sample/index.tsx
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  babel.config.js
  index.js
  ios/Podfile
  ios/Scalix-Bridging-Header.h
  package.json
Labels: enhancement

#186 [LM-10227] Product Signoff Bugs
  App.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/HomeFeedExplore/styles.ts
  ChatSX/components/HomeFeedItem/styles.ts
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ChatRoom/styles.ts
Labels: bug

#187 Version <> Release v1.7.0
  .env
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: release

#188 Release/v1.7.0
  .env
  App.tsx
  ChatSX/assets/images/cross_circle_icon3x.png
  ChatSX/assets/images/left_chevron_icon3x.png
  ChatSX/assets/images/link_icon.png
  ChatSX/assets/images/mic_icon3x.png
  ChatSX/assets/images/pause_icon3x.png
  ChatSX/assets/images/play_icon3x.png
  ChatSX/assets/images/record_icon3x.png
  ChatSX/assets/images/retry_cloud_upload3x.png
  ChatSX/assets/images/stop_recording_icon3x.png
  ChatSX/assets/images/up_chevron_icon3x.png
  ChatSX/assets/lottieJSON/delete.json
  ChatSX/audio/Controls.ts
  ChatSX/audio/TrackPlayerServices.ts
  ChatSX/audio/Utils.ts
  ChatSX/audio/index.ts
  ChatSX/aws-exports.js
  ChatSX/commonFuctions/index.tsx
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/AttachmentConversations/styles.ts
  ChatSX/components/HomeFeedExplore/styles.ts
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/HomeFeedItem/styles.ts
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/InputBox/models/InputBoxProps.ts
  ChatSX/components/InputBox/models/VoiceNotesPlayerProps.ts
  ChatSX/components/InputBox/models/VoiceNotesProps.ts
  ChatSX/components/InputBox/models/index.tsx
  ChatSX/components/InputBox/styles.ts
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/constants/Strings.ts
  ChatSX/db/models/UserInfo.ts
  ChatSX/db/models/index.tsx
  ChatSX/enums/DocumentType.ts
  ChatSX/enums/GetConversationsType.ts
  ChatSX/enums/MemberState.ts
  ChatSX/enums/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ChatRoom/styles.ts
  ChatSX/store/reducers/chatroomReducer.ts
  ChatSX/store/types/types.ts
  ChatSX/utils/chatroomUtils.ts
  ChatSX/utils/permissions.ts
  ChatSX/utils/syncChatroomApi.ts
  Sample/index.tsx
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  babel.config.js
  index.js
  ios/Podfile
  ios/Scalix-Bridging-Header.h
  ios/Scalix/Info.plist
  package.json
Labels: release

#193 [LM-10270] Master Fixes and client regarding changes
  .env
  App.tsx
  ChatSX/LMChatApp.tsx
  ChatSX/RootNavigation.js
  ChatSX/components/AttachmentConversations/index.tsx
  ChatSX/components/CommonAllMembers/index.tsx
  ChatSX/components/ExploreFeedFilters/index.tsx
  ChatSX/components/ExploreFeedItem/index.tsx
  ChatSX/components/HomeFeedItem/index.tsx
  ChatSX/components/ImageScreen/index.tsx
  ChatSX/components/InputBox/index.tsx
  ChatSX/components/LinkPreview/index.tsx
  ChatSX/components/Messages/index.tsx
  ChatSX/components/ParseDeepLink/index.ts
  ChatSX/components/Poll/CreatePollScreen/index.tsx
  ChatSX/components/Poll/PollConversationView/index.tsx
  ChatSX/components/ReplyConversations/index.tsx
  ChatSX/components/TopTabNavigator/index.tsx
  ChatSX/credentials.ts
  ChatSX/enums/index.tsx
  ChatSX/navigation/SwitchComponent/index.tsx
  ChatSX/screens/CarouselScreen/index.tsx
  ChatSX/screens/ChatRoom/index.tsx
  ChatSX/screens/ExploreFeed/index.tsx
  ChatSX/screens/FIleUpload/index.tsx
  ChatSX/screens/HomeFeed/Tabs/DMFeed/index.tsx
  ChatSX/screens/HomeFeed/Tabs/GroupFeed/index.tsx
  ChatSX/screens/HomeFeed/index.tsx
  ChatSX/screens/ImageCrop/index.tsx
  ChatSX/screens/ReportMessage/index.tsx
  ChatSX/screens/ViewParticipants/index.tsx
  ChatSX/setup.ts
  ChatSX/store.ts
  ChatSX/utils/syncChatroomApi.ts
  Sample/index.tsx
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
  tsconfig.json
Labels: hotfix

#194 [LM-10270] Fixed misses in code
  .env
  ChatSX/LMChatApp.tsx
  ChatSX/navigation/SwitchComponent/index.tsx
  ChatSX/setup.ts
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: hotfix

#196 [LM-10270] Fixed Keyboard Overlapping Issue
  .env
  ChatSX/LMChatApp.tsx
  ChatSX/setup.ts
  android/app/build.gradle
  index.js
  ios/Scalix/Info.plist
  package.json
Labels: hotfix
